version: "3.9"

services:
  # Remote/production services
  backend:
    image: ${PYGEOAPI_IMAGE:-ghcr.io/yejiyang/pygeoapi-w-global-tsunami-data:latest}
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_OPENAPI=/tmp/openapi.yml
      - CONTAINER_NAME=pygeoapi
      - CONTAINER_HOST=0.0.0.0
      - CONTAINER_PORT=5000
      - PYGEOAPI_SERVER_URL=${PYGEOAPI_SERVER_URL:-http://localhost:5000}

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/yejiyang/global-tsunami-risk-map-frontend:latest}
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://backend:5000}
    depends_on:
      - backend

  # Local development services
  backend-local:
    image: geopython-api:latest
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml
    environment:
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_OPENAPI=/tmp/openapi.yml
      - CONTAINER_NAME=pygeoapi
      - CONTAINER_HOST=0.0.0.0
      - CONTAINER_PORT=5000
      - PYGEOAPI_SERVER_URL=http://localhost:5000
      #- APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=b4d987bc-1712-4026-aafb-f590fd854ab3;IngestionEndpoint=https://norwayeast-0.in.applicationinsights.azure.com/;LiveEndpoint=https://norwayeast.livediagnostics.monitor.azure.com/;ApplicationId=9fc4692c-7609-4abb-b547-49203ac14d4a
    profiles:
      - local

  frontend-local:
    image: local/global-tsunami-risk-map-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_BASE_URL=http://backend-local:5000
    depends_on:
      - backend-local
    profiles:
      - local
